openapi: 3.0.2

info: 
  title: i-sense flu backend
  description: Backend API for the i-sense flu web app
  version: v2.0
  
paths:
  /:
    get:
      summary: Returns the scores for the default flu model
      responses:
        '200':
          $ref: 'components/responses.yaml#/modelsAndMetadata'
        '404':
          description: No public model scores available
        '503':
          description: Resource unavailable
  /models:
    get:
      summary: Returns a list of public models
      responses:
        '200':
          $ref: 'components/responses.yaml#/modelList'
        '404':
          description: No public models available
        '503':
          description: Resource unavailable
  /plink:
    get:
      summary: Returns the scores and metadata for one or more models in a specific time window
      parameters:
        - $ref: 'components/parameters.yaml#/idRef'
          required: true
        - $ref: 'components/parameters.yaml#/startDateRef'
          required: true
        - $ref: 'components/parameters.yaml#/endDateRef'
          required: true
        - $ref: 'components/parameters.yaml#/resolutionRef'
          required: true
        - $ref: 'components/parameters.yaml#/smoothingRef'
          required: true
      responses:
        '200':
          $ref: 'components/responses.yaml#/modelsAndMetadata'
        '404':
          description: Not found. Model data no longer available
        '503':
          description: Resource unavailable
  /scores:
    get:
      summary: Returns the scores for one or more models in a specific time window
      parameters:
        - $ref: 'components/parameters.yaml#/idRef'
          required: true
        - $ref: 'components/parameters.yaml#/startDateRef'
          required: true
        - $ref: 'components/parameters.yaml#/endDateRef'
          required: true
        - $ref: 'components/parameters.yaml#/resolutionRef'
        - $ref: 'components/parameters.yaml#/smoothingRef'
      responses:
        '200':
          $ref: 'components/responses.yaml#/modelDataAndScores'
        '404':
          description: No scores found
        '503':
          description: Resource unavailable
  /twlink:
    get:
      summary: Returns the scores and metadata for a model linked from Twitter
      parameters:
        - $ref: 'components/parameters.yaml#/legacyIdRef'
          required: true
        - $ref: 'components/parameters.yaml#/startDateRef'
          required: true
        - $ref: 'components/parameters.yaml#/endDateRef'
          required: true
        - $ref: 'components/parameters.yaml#/resolutionRef'
          required: true
        - $ref: 'components/parameters.yaml#/smoothingRef'
          required: true
      responses:
        '200':
          $ref: 'components/responses.yaml#/modelsAndMetadata'
        '404':
          description: Not found. Model data no longer available
        '503':
          description: Resource unavailable
          